/**
 * 父项目「自动生成 年/月/周 子项目」逻辑
 *
 * 当一个项目开启 autoChildren 后，按日期自动派生两层子项目：
 *   - 月项目：`<year>年<month>月`（如 2026年8月）
 *   - 周项目：`<startM>月<startD>日-<endM>月<endD>日`（如 8月24日-8月30日）
 *       · 周以「周一」为起点、「周日」为终点
 *       · 跨月周归入「起始日所在月」的月项目下（如 8月31日-9月6日 → 挂在 2026年8月 下）
 *
 * 这些子项目只是承载自动生成任务的容器，用户也可手动往里加任务。
 * 采用「按需生成」策略：resolveWeekProjectForDate 在任务生成时被调用，
 * 给定某天返回其所属周子项目 id（不存在则创建月+周两层），不预先批量建结构。
 */
import { db } from './db'

function pad(n) {
  return String(n).padStart(2, '0')
}

/** 返回 date 所在「周一~周日」的起止 Date（已清零时分秒） */
export function weekRangeOf(date) {
  const d = new Date(date)
  d.setHours(0, 0, 0, 0)
  const dow = d.getDay() // 0=周日 .. 6=周六
  const diffToMon = dow === 0 ? -6 : 1 - dow
  const start = new Date(d)
  start.setDate(d.getDate() + diffToMon)
  const end = new Date(start)
  end.setDate(start.getDate() + 6)
  return { start, end }
}

export function monthProjectName(d) {
  return `${d.getFullYear()}年${d.getMonth() + 1}月`
}
export function weekProjectName(start, end) {
  return `${start.getMonth() + 1}月${pad(start.getDate())}日-${end.getMonth() + 1}月${pad(end.getDate())}日`
}

/** 在 parentId 下按 name 查找已存在的子项目 */
async function findChild(parentId, name) {
  const all = await db.projects.toArray()
  return all.find((p) => (p.parentId || null) === (parentId || null) && p.name === name)
}

/** 在 parentId 下按 name 查找/创建子项目，返回 id */
async function ensureChild(parentId, name, color) {
  const found = await findChild(parentId, name)
  if (found) return found.id
  const all = await db.projects.toArray()
  const maxOrder = all.reduce((m, p) => Math.max(m, p.order ?? 0), 0)
  return await db.projects.add({
    name,
    color: color || '#8b5cf6',
    parentId: parentId || null,
    progressMode: 'auto',
    manualProgress: 0,
    order: maxOrder + 1,
    archived: 0,
    startAt: null,
    endAt: null,
    createdAt: Date.now(),
    autoGenerated: 1
  })
}

/**
 * 给定父项目 id 与日期，返回该日期所属「周子项目」的 id（不存在则创建月+周两层）。
 * @returns {Promise<number|null>}
 */
export async function resolveWeekProjectForDate(parentId, dateStr) {
  if (!parentId) return null
  const d = new Date(`${dateStr}T00:00:00`)
  if (Number.isNaN(d.getTime())) return null
  const { start, end } = weekRangeOf(d)
  const monthId = await ensureChild(parentId, monthProjectName(start), '#8b5cf6')
  const weekId = await ensureChild(monthId, weekProjectName(start, end), '#06b6d4')
  return weekId
}
